### ISSUE TITLE
`make dev` failure on Mac OS 12.1 (Monterey) and Apple Silicon

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/viahtml#287]
The failures I'm seeing on `make dev` on my new Silicon-based MacBook Pro aren't like the other failures I'm seeing (which are rectified by updating the `.python_version` to something >= `3.8.10`). If I update `viahtml`'s local `.python_version` to indicate `3.8.12` (same version as Dockerfile indicates), running `make dev` gives me a wall o' hate.

There is no particular urgency on this one for me as I very rarely run `viahtml` ( I run `via` and test LMS with PDF assignments).

```
 build/temp.macosx-12.1-arm64-3.8/_openssl.c:575:10: fatal error: 'openssl/opensslv.h' file not found
  #include <openssl/opensslv.h>
           ^~~~~~~~~~~~~~~~~~~~
  1 error generated.

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      =============================DEBUG ASSISTANCE=============================

  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
  Building wheel for gevent (pyproject.toml): started
  Building wheel for gevent (pyproject.toml): still running...
  Building wheel for gevent (pyproject.toml): finished with status 'done'
  Created wheel for gevent: filename=gevent-20.9.0-cp38-cp38-macosx_12_0_arm64.whl size=1630903 sha256=331ec68ec29810f33badcb3cf33a6c5426a66a3df629ee48fdf327d2b68c9ec2
  Stored in directory: /Users/lyza/Library/Caches/pip/wheels/4e/e6/9b/eeb63e29d5011f03cd609aaf87a6b4e2b17003ff60cbcf9a8f
  Building wheel for py3amf (setup.py): started
  Building wheel for py3amf (setup.py): finished with status 'done'
  Created wheel for py3amf: filename=Py3AMF-0.8.10-py3-none-any.whl size=200471 sha256=b7218482e5570f6c4e489382272673251c9358d4546d98418b335cccba25de8b
  Stored in directory: /Users/lyza/Library/Caches/pip/wheels/8e/44/9d/c259cd81b29bf6c2d0fd4e928606ff66662e0c7eb882654e90
  Building wheel for pyyaml (pyproject.toml): started
  Building wheel for pyyaml (pyproject.toml): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.4-cp38-cp38-macosx_12_0_arm64.whl size=45529 sha256=ea5c8bfee7710d32032b7a69a8a4928654eb350b7cd02129a4cbe2715a7d76f3
  Stored in directory: /Users/lyza/Library/Caches/pip/wheels/89/b4/5f/cb055d6b1decb1050d7a3620abf3bca515f16d28e8c42ae23e
  Building wheel for surt (setup.py): started
  Building wheel for surt (setup.py): finished with status 'done'
  Created wheel for surt: filename=surt-0.3.1-py3-none-any.whl size=14559 sha256=3c804c0d17cbfae6d07cb27c9fa2810b9bf140d464217aaa1e917ff5d34a4101
  Stored in directory: /Users/lyza/Library/Caches/pip/wheels/6f/e7/29/bf08047f4eaff6dc15078be5ce54023a2cfd2a0cdeea6ffe0e
  Building wheel for uwsgi (setup.py): started
  Building wheel for uwsgi (setup.py): finished with status 'done'
  Created wheel for uwsgi: filename=uWSGI-2.0.20-cp38-cp38-macosx_12_0_arm64.whl size=1554609 sha256=a3b43b369fe654e605e837d280972938ec1974a042eaff6721160636ad3e4bb4
  Stored in directory: /Users/lyza/Library/Caches/pip/wheels/cb/4d/54/002a215100a8c4e125654600f0a4304dae742442ddc4ba6ea1
  Building wheel for webassets (setup.py): started
  Building wheel for webassets (setup.py): finished with status 'done'
  Created wheel for webassets: filename=webassets-0.12.1-py3-none-any.whl size=136809 sha256=31356a2ff7a6388d948472633a8b3617dd3c2938e0ecb07dc59369f7996cce99
  Stored in directory: /Users/lyza/Library/Caches/pip/wheels/10/e2/04/23353900659c0fb9984fe285abb4f0e83abfef2bb3fda10a61
Successfully built brotlipy cffi gevent py3amf pyyaml surt uwsgi webassets
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "/Users/lyza/Projects/viahtml/.tox/dev/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
  File "/Users/lyza/Projects/viahtml/.tox/dev/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lyza/Projects/viahtml/.tox/dev/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/lyza/Projects/viahtml/.tox/dev/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lyza/Projects/viahtml/.tox/dev/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lyza/Projects/viahtml/.tox/dev/lib/python3.8/site-packages/piptools/scripts/sync.py", line 178, in cli
    sync.sync(
  File "/Users/lyza/Projects/viahtml/.tox/dev/lib/python3.8/site-packages/piptools/sync.py", line 248, in sync
    run(  # nosec
  File "/Users/lyza/.pyenv/versions/3.8.12/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/lyza/Projects/viahtml/.tox/dev/bin/python', '-m', 'pip', 'install', '-r', '/var/folders/6k/pcljxwxn2c971cs4qw_y46hc0000gn/T/tmp37675pbj']' returned non-zero exit status 1.

=================================== log end ====================================
ERROR: could not install deps [-rrequirements/dev.txt]; v = InvocationError('/Users/lyza/Projects/viahtml/.tox/dev/bin/pip-sync requirements/dev.txt', 1)
___________________________________ summary ____________________________________
ERROR:   dev: could not install deps [-rrequirements/dev.txt]; v = InvocationError('/Users/lyza/Projects/viahtml/.tox/dev/bin/pip-sync requirements/dev.txt', 1)
make: *** [dev] Error 1
```

**Comment by marcospri** [comment]
Python version has been updated to the latest 3.8 version since:

https://github.com/hypothesis/viahtml/commit/be772a24119f5e858d369d55bb1ef54a5f31c15f
